# =============================================================================
# 04d_el_derivation_iecv.R — DEPRECATED (v3.0 Pure E-only Design)
# IDH EBM Governance — Plan A Phase 2
#
# ⚠ THIS SCRIPT IS NO LONGER NEEDED.
#
# Under the pure E-only design (v3.0), 03_iecv_ebm.R performs E-only
# hyperparameter tuning, training, and external validation directly.
# All artifacts previously produced by this script are now generated by 03:
#   - E-only EBM models (.joblib)     → RUN_DIR/Iter*/*_Final_EBM.joblib
#   - E-only thresholds & artifacts   → RUN_DIR/Iter*/*_artifacts.rds
#   - Shape function exports          → RUN_DIR/Iter*/Shapes/
#
# The downstream confirmatory script (04f_el_confirmatory.R) has been updated
# to read directly from RUN_DIR instead of EL_DIR_DERIVATION.
#
# This shim exists for backward compatibility only. Running it will print
# a notice and exit without performing any computation.
#
# History:
#   v2.x — E-only IECV with HP inherited from full-cohort (EL_SKIP_GRID_SEARCH)
#   v3.0 — Superseded by 03_iecv_ebm.R v3.0 (pure E-only from the start)
# =============================================================================

if (!exists("SITE_FILES")) src("R/00_config.R")

cat("\n")
cat(paste(rep("=", 70), collapse = ""), "\n")
cat("  Module 04d: DEPRECATED — Superseded by 03_iecv_ebm.R v3.0\n")
cat(paste(rep("=", 70), collapse = ""), "\n\n")

cat("  Under the pure E-only design, 03_iecv_ebm.R now performs all\n")
cat("  E-only hyperparameter tuning, training, and validation.\n")
cat("  This script is no longer needed.\n\n")

cat(sprintf("  E-only artifacts location: %s\n", RUN_DIR))

# Verify that 03's output exists
iter_dirs <- list.dirs(RUN_DIR, recursive = FALSE, full.names = TRUE)
iter_dirs <- iter_dirs[grepl("^Iter\\d+_External_", basename(iter_dirs))]

if (length(iter_dirs) > 0) {
  cat(sprintf("  Found %d E-only IECV iterations in RUN_DIR.\n", length(iter_dirs)))
  for (d in iter_dirs) {
    models <- list.files(d, pattern = "_Final_EBM\\.joblib$")
    arts   <- list.files(d, pattern = "_artifacts\\.rds$")
    cat(sprintf("    %s: model=%s, artifacts=%s\n",
                basename(d),
                ifelse(length(models) > 0, "OK", "MISSING"),
                ifelse(length(arts)   > 0, "OK", "MISSING")))
  }
  cat("\n  → Downstream scripts (04e, 04f) can proceed using RUN_DIR.\n")
} else {
  cat("  [WARNING] No IECV iterations found in RUN_DIR.\n")
  cat("  → Run 03_iecv_ebm.R v3.0 first.\n")
}

cat("\n  Module 04d (deprecated shim) complete.\n\n")
